apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-cicd-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: k8s-cicd-demo

  template:
    metadata:
      labels:
        app: k8s-cicd-demo

    spec:
      containers:
      - name: app
        image: gamemaster007/k8s-cicd-demo:v1
        ports:
        - containerPort: 3000
